version: 2.1

orbs:
  go: circleci/go@1.7.3

jobs:
  radiant:
    docker:
      - image: cimg/go:1.20.6
    steps:
      - checkout
      - go/install:
          cache: true
      - run:
          command: go run radiant.go

workflows:
  poll:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - radiant
