version: 2.1

jobs:
  radiant:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - install:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
      - run: go build .
      - run: ./radiant

workflows:
  version: 2
  build-deploy:
    jobs:
      - radiant
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - main
