version: 2.1

jobs:
  radiant:
    docker:
      - image: cimg/go:1.20.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - install:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
      - run:
          name: Run Scraper
          command: go run radiant.go

workflows:
  poll:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - radiant
