version: 2.1

executors:
  golang:
    docker:
      - image: 'golang:1.20.6'
    working_directory: /go/src/github.com/chakrakan/radiant

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: go mod download
      - run: go run radiant.go

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - main
